"""DrugBank 映射模組"""

import re
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import pandas as pd

from .normalizer import extract_ingredients, get_all_synonyms


def load_drugbank_vocab(filepath: Optional[Path] = None) -> pd.DataFrame:
    """載入 DrugBank 詞彙表

    Args:
        filepath: CSV 檔案路徑，預設為 data/external/drugbank_vocab.csv

    Returns:
        DrugBank 詞彙表 DataFrame
    """
    if filepath is None:
        filepath = Path(__file__).parent.parent.parent.parent / "data" / "external" / "drugbank_vocab.csv"

    return pd.read_csv(filepath)


def build_name_index(drugbank_df: pd.DataFrame) -> Dict[str, str]:
    """建立名稱索引（名稱 -> DrugBank ID）

    Args:
        drugbank_df: DrugBank 詞彙表

    Returns:
        名稱到 ID 的對照字典
    """
    index = {}

    for _, row in drugbank_df.iterrows():
        name_upper = row["drug_name_upper"]
        drugbank_id = row["drugbank_id"]

        # 完整名稱
        index[name_upper] = drugbank_id

        # 移除常見鹽類後綴，建立別名
        # 例如 "METFORMIN HCL" -> "METFORMIN"
        salt_suffixes = [
            " HCL", " HYDROCHLORIDE", " SODIUM", " POTASSIUM",
            " SULFATE", " SULPHATE", " MALEATE", " ACETATE",
            " CITRATE", " PHOSPHATE", " BROMIDE", " CHLORIDE",
            " TARTRATE", " FUMARATE", " SUCCINATE", " MESYLATE",
            " BESYLATE", " CALCIUM", " MAGNESIUM", " NITRATE",
            " LACTATE", " GLUCONATE", " DISODIUM", " MONOHYDRATE",
            " DIHYDRATE", " TRIHYDRATE", " ANHYDROUS",
            " DIPROPIONATE", " PROPIONATE", " ACETONIDE",
            " VALERATE", " BUTYRATE", " HEXAHYDRATE",
        ]

        for suffix in salt_suffixes:
            if name_upper.endswith(suffix):
                base_name = name_upper[:-len(suffix)].strip()
                if base_name and base_name not in index:
                    index[base_name] = drugbank_id

    # 添加常見同義詞對照（完全匹配優先）
    synonym_map = {
        # 維生素 - 多種名稱對應
        "NIACINAMIDE": "NICOTINAMIDE",
        "NICOTINIC ACID": "NIACIN",
        "VITAMIN B3": "NIACIN",
        "PYRIDOXINE": "PYRIDOXINE",  # DrugBank 用這個
        "VITAMIN B6": "PYRIDOXINE",
        "THIAMINE": "THIAMINE",  # DrugBank 用這個
        "VITAMIN B1": "THIAMINE",
        "ANEURINE": "THIAMINE",
        "RIBOFLAVIN": "RIBOFLAVIN",  # DrugBank 用這個
        "VITAMIN B2": "RIBOFLAVIN",
        "CYANOCOBALAMIN": "CYANOCOBALAMIN",  # DrugBank 用這個
        "VITAMIN B12": "CYANOCOBALAMIN",
        "COBALAMIN": "CYANOCOBALAMIN",
        "ASCORBIC ACID": "ASCORBIC ACID",  # DrugBank 用這個
        "VITAMIN C": "ASCORBIC ACID",
        "TOCOPHEROL": "VITAMIN E",
        "ALPHA-TOCOPHEROL": "VITAMIN E",
        "RETINOL": "VITAMIN A",
        "RETINYL PALMITATE": "VITAMIN A",
        "CHOLECALCIFEROL": "CHOLECALCIFEROL",  # DrugBank 用這個
        "VITAMIN D3": "CHOLECALCIFEROL",
        "COLECALCIFEROL": "CHOLECALCIFEROL",
        "ERGOCALCIFEROL": "ERGOCALCIFEROL",  # DrugBank 用這個
        "VITAMIN D2": "ERGOCALCIFEROL",
        "PHYTONADIONE": "PHYTONADIONE",  # DrugBank 用這個
        "VITAMIN K1": "PHYTONADIONE",
        "PHYLLOQUINONE": "PHYTONADIONE",
        "FOLIC ACID": "FOLIC ACID",  # DrugBank 用這個
        "FOLATE": "FOLIC ACID",
        "VITAMIN B9": "FOLIC ACID",
        "BIOTIN": "BIOTIN",
        "VITAMIN B7": "BIOTIN",
        "VITAMIN H": "BIOTIN",
        "PANTOTHENIC ACID": "PANTOTHENIC ACID",
        "VITAMIN B5": "PANTOTHENIC ACID",

        # 常見藥物國際別名
        "ACETYLSALICYLIC ACID": "ASPIRIN",
        "PARACETAMOL": "ACETAMINOPHEN",
        "ADRENALINE": "EPINEPHRINE",
        "NORADRENALINE": "NOREPINEPHRINE",
        "LIGNOCAINE": "LIDOCAINE",
        "XYLOCAINE": "LIDOCAINE",
        "FRUSEMIDE": "FUROSEMIDE",
        "SALBUTAMOL": "ALBUTEROL",
        "METAMIZOLE": "DIPYRONE",
        "DIPYRONE": "DIPYRONE",
        "GLIBENCLAMIDE": "GLYBURIDE",
        "CICLOSPORIN": "CYCLOSPORINE",
        "CICLOSPORINA": "CYCLOSPORINE",

        # 電解質/礦物質
        "SODIUM CHLORIDE": "SODIUM CHLORIDE",
        "SALINE": "SODIUM CHLORIDE",
        "POTASSIUM CHLORIDE": "POTASSIUM CHLORIDE",
        "CALCIUM CHLORIDE": "CALCIUM CHLORIDE",
        "MAGNESIUM CHLORIDE": "MAGNESIUM CHLORIDE",
        "SODIUM BICARBONATE": "SODIUM BICARBONATE",
        "CALCIUM CARBONATE": "CALCIUM CARBONATE",
        "MAGNESIUM SULFATE": "MAGNESIUM SULFATE",
        "EPSOM SALT": "MAGNESIUM SULFATE",
        "FERROUS SULFATE": "FERROUS SULFATE",
        "IRON SULFATE": "FERROUS SULFATE",
        "ZINC SULFATE": "ZINC SULFATE",
        "ZINC OXIDE": "ZINC OXIDE",

        # L-/D-/DL- 前綴處理
        "L-MENTHOL": "MENTHOL",
        "DL-MENTHOL": "MENTHOL",
        "LEVOMENTHOL": "MENTHOL",
        "L-ADRENALINE": "EPINEPHRINE",
        "L-NORADRENALINE": "NOREPINEPHRINE",
        "L-DOPA": "LEVODOPA",
        "L-THYROXINE": "LEVOTHYROXINE",
        "LEVO-THYROXINE": "LEVOTHYROXINE",

        # 水合物/無水 - 對應到基本形式
        "CAFFEINE ANHYDROUS": "CAFFEINE",
        "DEXTROSE MONOHYDRATE": "GLUCOSE",
        "DEXTROSE": "GLUCOSE",
        "GLUCOSE MONOHYDRATE": "GLUCOSE",
        "GLUCOSE ANHYDROUS": "GLUCOSE",
        "LACTOSE MONOHYDRATE": "LACTOSE",
        "LACTOSE ANHYDROUS": "LACTOSE",
        "CALCIUM CHLORIDE DIHYDRATE": "CALCIUM CHLORIDE",
        "MAGNESIUM CHLORIDE HEXAHYDRATE": "MAGNESIUM CHLORIDE",
        "SODIUM PHOSPHATE DIBASIC": "SODIUM PHOSPHATE",
        "SODIUM PHOSPHATE MONOBASIC": "SODIUM PHOSPHATE",

        # 鹽類變體 - 對應到 DrugBank 常用形式
        "METFORMIN HYDROCHLORIDE": "METFORMIN",
        "METFORMIN HCL": "METFORMIN",
        "AMLODIPINE BESYLATE": "AMLODIPINE",
        "AMLODIPINE BESILATE": "AMLODIPINE",
        "ATORVASTATIN CALCIUM": "ATORVASTATIN",
        "OMEPRAZOLE SODIUM": "OMEPRAZOLE",
        "OMEPRAZOLE MAGNESIUM": "OMEPRAZOLE",
        "PANTOPRAZOLE SODIUM": "PANTOPRAZOLE",
        "ESOMEPRAZOLE MAGNESIUM": "ESOMEPRAZOLE",
        "ESOMEPRAZOLE SODIUM": "ESOMEPRAZOLE",
        "LOSARTAN POTASSIUM": "LOSARTAN",
        "CLOPIDOGREL BISULFATE": "CLOPIDOGREL",
        "CLOPIDOGREL HYDROGEN SULFATE": "CLOPIDOGREL",
        "MONTELUKAST SODIUM": "MONTELUKAST",
        "SERTRALINE HYDROCHLORIDE": "SERTRALINE",
        "FLUOXETINE HYDROCHLORIDE": "FLUOXETINE",
        "VENLAFAXINE HYDROCHLORIDE": "VENLAFAXINE",
        "DULOXETINE HYDROCHLORIDE": "DULOXETINE",
        "TRAMADOL HYDROCHLORIDE": "TRAMADOL",
        "MORPHINE SULFATE": "MORPHINE",
        "CODEINE PHOSPHATE": "CODEINE",
        "OXYCODONE HYDROCHLORIDE": "OXYCODONE",
        "FENTANYL CITRATE": "FENTANYL",
        "LIDOCAINE HYDROCHLORIDE": "LIDOCAINE",
        "BUPIVACAINE HYDROCHLORIDE": "BUPIVACAINE",
        "AMOXICILLIN TRIHYDRATE": "AMOXICILLIN",
        "AMPICILLIN SODIUM": "AMPICILLIN",
        "AMPICILLIN TRIHYDRATE": "AMPICILLIN",
        "CEFTRIAXONE SODIUM": "CEFTRIAXONE",
        "AZITHROMYCIN DIHYDRATE": "AZITHROMYCIN",
        "CIPROFLOXACIN HYDROCHLORIDE": "CIPROFLOXACIN",
        "LEVOFLOXACIN HEMIHYDRATE": "LEVOFLOXACIN",
        "VANCOMYCIN HYDROCHLORIDE": "VANCOMYCIN",
        "GENTAMICIN SULFATE": "GENTAMICIN",
        "NEOMYCIN SULFATE": "NEOMYCIN",
        "TOBRAMYCIN SULFATE": "TOBRAMYCIN",
        "PREDNISONE ACETATE": "PREDNISONE",
        "PREDNISOLONE ACETATE": "PREDNISOLONE",
        "PREDNISOLONE SODIUM PHOSPHATE": "PREDNISOLONE",
        "DEXAMETHASONE SODIUM PHOSPHATE": "DEXAMETHASONE",
        "DEXAMETHASONE ACETATE": "DEXAMETHASONE",
        "BETAMETHASONE VALERATE": "BETAMETHASONE",
        "BETAMETHASONE DIPROPIONATE": "BETAMETHASONE",
        "HYDROCORTISONE ACETATE": "HYDROCORTISONE",
        "HYDROCORTISONE SODIUM SUCCINATE": "HYDROCORTISONE",
        "TRIAMCINOLONE ACETONIDE": "TRIAMCINOLONE",
        "FLUTICASONE PROPIONATE": "FLUTICASONE",
        "FLUTICASONE FUROATE": "FLUTICASONE",
        "BUDESONIDE": "BUDESONIDE",
        "BECLOMETHASONE DIPROPIONATE": "BECLOMETHASONE",
        "MOMETASONE FUROATE": "MOMETASONE",
        "PHENYLEPHRINE HYDROCHLORIDE": "PHENYLEPHRINE",
        "PSEUDOEPHEDRINE HYDROCHLORIDE": "PSEUDOEPHEDRINE",
        "EPINEPHRINE HYDROCHLORIDE": "EPINEPHRINE",
        "DOPAMINE HYDROCHLORIDE": "DOPAMINE",
        "DOBUTAMINE HYDROCHLORIDE": "DOBUTAMINE",
        "ATROPINE SULFATE": "ATROPINE",
        "GLYCINE": "GLYCINE",
        "ALANINE": "ALANINE",
        "L-ALANINE": "ALANINE",
        "VALINE": "VALINE",
        "L-VALINE": "VALINE",
        "LEUCINE": "LEUCINE",
        "L-LEUCINE": "LEUCINE",
        "ISOLEUCINE": "ISOLEUCINE",
        "L-ISOLEUCINE": "ISOLEUCINE",
        "PROLINE": "PROLINE",
        "L-PROLINE": "PROLINE",
        "SERINE": "SERINE",
        "L-SERINE": "SERINE",
        "THREONINE": "THREONINE",
        "L-THREONINE": "THREONINE",
        "CYSTEINE": "CYSTEINE",
        "L-CYSTEINE": "CYSTEINE",
        "METHIONINE": "METHIONINE",
        "L-METHIONINE": "METHIONINE",
        "PHENYLALANINE": "PHENYLALANINE",
        "L-PHENYLALANINE": "PHENYLALANINE",
        "TYROSINE": "TYROSINE",
        "L-TYROSINE": "TYROSINE",
        "TRYPTOPHAN": "TRYPTOPHAN",
        "L-TRYPTOPHAN": "TRYPTOPHAN",
        "HISTIDINE": "HISTIDINE",
        "L-HISTIDINE": "HISTIDINE",
        "LYSINE": "LYSINE",
        "L-LYSINE": "LYSINE",
        "ARGININE": "ARGININE",
        "L-ARGININE": "ARGININE",
        "GLUTAMINE": "GLUTAMINE",
        "L-GLUTAMINE": "GLUTAMINE",
        "GLUTAMIC ACID": "GLUTAMIC ACID",
        "L-GLUTAMIC ACID": "GLUTAMIC ACID",
        "ASPARTIC ACID": "ASPARTIC ACID",
        "L-ASPARTIC ACID": "ASPARTIC ACID",
        "ASPARAGINE": "ASPARAGINE",
        "L-ASPARAGINE": "ASPARAGINE",
        "CAMPHOR": "CAMPHOR",
        "D-CAMPHOR": "CAMPHOR",
        "DL-CAMPHOR": "CAMPHOR",

        # 空格/無空格變體
        "ETHINYL ESTRADIOL": "ETHINYLESTRADIOL",
        "ETHINYLESTRADIOL": "ETHINYLESTRADIOL",

        # GLUCOSE 變體
        "GLUCOSE": "D-GLUCOSE",
        "DEXTROSE": "D-GLUCOSE",
        "GLUCOSE ANHYDROUS": "D-GLUCOSE",
        "GLUCOSE MONOHYDRATE": "D-GLUCOSE",

        # 酸/鹽變體
        "CLAVULANATE": "CLAVULANIC ACID",
        "CLAVULANATE POTASSIUM": "CLAVULANIC ACID",
        "POTASSIUM CLAVULANATE": "CLAVULANIC ACID",

        # 更多藥物變體
        "GUAIFENESIN": "GUAIFENESIN",
        "GUAIFENESINA": "GUAIFENESIN",
        "OLMESARTAN MEDOXOMIL": "OLMESARTAN",
        "TINIDAZOLE": "TINIDAZOLE",
        "ALBENDAZOLE": "ALBENDAZOLE",
        "MEBENDAZOLE": "MEBENDAZOLE",
        "IVERMECTIN": "IVERMECTIN",
        "NITAZOXANIDE": "NITAZOXANIDE",
        "BETAHISTINE": "BETAHISTINE",
        "BETAHISTINE DIHYDROCHLORIDE": "BETAHISTINE",
        "CYPROTERONE": "CYPROTERONE",
        "CYPROTERONE ACETATE": "CYPROTERONE",
        "MEDROXYPROGESTERONE": "MEDROXYPROGESTERONE",
        "MEDROXYPROGESTERONE ACETATE": "MEDROXYPROGESTERONE",
        "BACITRACIN": "BACITRACIN",
        "BACITRACIN ZINC": "BACITRACIN",
        "POLYMYXIN B": "POLYMYXIN B",
        "POLYMYXIN B SULFATE": "POLYMYXIN B",
        "KETOROLAC": "KETOROLAC",
        "KETOROLAC TROMETHAMINE": "KETOROLAC",
        "DESVENLAFAXINE": "DESVENLAFAXINE",
        "DESVENLAFAXINE SUCCINATE": "DESVENLAFAXINE",
        "QUETIAPINE": "QUETIAPINE",
        "QUETIAPINE FUMARATE": "QUETIAPINE",
        "QUETIAPINE HEMIFUMARATE": "QUETIAPINE",
        "LISDEXAMFETAMINE": "LISDEXAMFETAMINE",
        "LISDEXAMFETAMINE DIMESYLATE": "LISDEXAMFETAMINE",
        "SCOPOLAMINE": "SCOPOLAMINE",
        "SCOPOLAMINE BUTYLBROMIDE": "SCOPOLAMINE",
        "SCOPOLAMINE HYDROBROMIDE": "SCOPOLAMINE",
        "DIOSMIN": "DIOSMIN",
        "HESPERIDIN": "HESPERIDIN",
        "BROMOPRIDE": "BROMOPRIDE",

        # 抗生素變體
        "DOXYCYCLINE": "DOXYCYCLINE",
        "DOXYCYCLINE HYCLATE": "DOXYCYCLINE",
        "DOXYCYCLINE MONOHYDRATE": "DOXYCYCLINE",
        "MINOCYCLINE": "MINOCYCLINE",
        "MINOCYCLINE HYDROCHLORIDE": "MINOCYCLINE",
        "TIGECYCLINE": "TIGECYCLINE",

        # 更多皮質類固醇
        "PREDNISOLONE": "PREDNISOLONE",
        "PREDNISOLONE SODIUM PHOSPHATE": "PREDNISOLONE",
        "DEXAMETHASONE": "DEXAMETHASONE",
        "DEXAMETHASONE SODIUM PHOSPHATE": "DEXAMETHASONE",
        "DEXAMETHASONE PHOSPHATE": "DEXAMETHASONE",

        # ===== 葡萄牙文藥名 → 英文 (ANVISA 特有) =====

        # 常見藥物葡萄牙文名稱
        "ACETAMINOFENO": "ACETAMINOPHEN",
        "ACETAMINOFEM": "ACETAMINOPHEN",
        "PARACETAMOL": "ACETAMINOPHEN",
        "ACIDO ACETILSALICILICO": "ASPIRIN",
        "ÁCIDO ACETILSALICÍLICO": "ASPIRIN",
        "ADRENALINA": "EPINEPHRINE",
        "NORADRENALINA": "NOREPINEPHRINE",
        "LIDOCAINA": "LIDOCAINE",
        "FUROSEMIDA": "FUROSEMIDE",
        "RANITIDINA": "RANITIDINE",
        "OMEPRAZOL": "OMEPRAZOLE",
        "PANTOPRAZOL": "PANTOPRAZOLE",
        "ESOMEPRAZOL": "ESOMEPRAZOLE",
        "LANSOPRAZOL": "LANSOPRAZOLE",
        "RABEPRAZOL": "RABEPRAZOLE",

        # 抗生素葡萄牙文
        "AMOXICILINA": "AMOXICILLIN",
        "AMPICILINA": "AMPICILLIN",
        "PENICILINA": "PENICILLIN",
        "CEFALEXINA": "CEPHALEXIN",
        "CEFAZOLINA": "CEFAZOLIN",
        "CEFTRIAXONA": "CEFTRIAXONE",
        "CEFUROXIMA": "CEFUROXIME",
        "CEFEPIMA": "CEFEPIME",
        "CEFOTAXIMA": "CEFOTAXIME",
        "CEFTAZIDIMA": "CEFTAZIDIME",
        "AZITROMICINA": "AZITHROMYCIN",
        "ERITROMICINA": "ERYTHROMYCIN",
        "CLARITROMICINA": "CLARITHROMYCIN",
        "CIPROFLOXACINA": "CIPROFLOXACIN",
        "CIPROFLOXACINO": "CIPROFLOXACIN",
        "LEVOFLOXACINA": "LEVOFLOXACIN",
        "LEVOFLOXACINO": "LEVOFLOXACIN",
        "NORFLOXACINA": "NORFLOXACIN",
        "NORFLOXACINO": "NORFLOXACIN",
        "MOXIFLOXACINA": "MOXIFLOXACIN",
        "MOXIFLOXACINO": "MOXIFLOXACIN",
        "METRONIDAZOL": "METRONIDAZOLE",
        "VANCOMICINA": "VANCOMYCIN",
        "GENTAMICINA": "GENTAMICIN",
        "TOBRAMICINA": "TOBRAMYCIN",
        "AMICACINA": "AMIKACIN",
        "NEOMICINA": "NEOMYCIN",
        "ESTREPTOMICINA": "STREPTOMYCIN",
        "CLINDAMICINA": "CLINDAMYCIN",
        "LINEZOLIDA": "LINEZOLID",
        "DAPTOMICINA": "DAPTOMYCIN",
        "TEICOPLANINA": "TEICOPLANIN",
        "NITROFURANTOÍNA": "NITROFURANTOIN",
        "NITROFURANTOINA": "NITROFURANTOIN",
        "SULFAMETOXAZOL": "SULFAMETHOXAZOLE",
        "TRIMETOPRIMA": "TRIMETHOPRIM",

        # 抗真菌藥
        "FLUCONAZOL": "FLUCONAZOLE",
        "ITRACONAZOL": "ITRACONAZOLE",
        "CETOCONAZOL": "KETOCONAZOLE",
        "MICONAZOL": "MICONAZOLE",
        "CLOTRIMAZOL": "CLOTRIMAZOLE",
        "NISTATINA": "NYSTATIN",
        "ANFOTERICINA": "AMPHOTERICIN B",
        "TERBINAFINA": "TERBINAFINE",
        "GRISEOFULVINA": "GRISEOFULVIN",

        # 抗病毒藥
        "ACICLOVIR": "ACYCLOVIR",
        "VALACICLOVIR": "VALACYCLOVIR",
        "GANCICLOVIR": "GANCICLOVIR",
        "OSELTAMIVIR": "OSELTAMIVIR",
        "RIBAVIRINA": "RIBAVIRIN",
        "LAMIVUDINA": "LAMIVUDINE",
        "ZIDOVUDINA": "ZIDOVUDINE",
        "TENOFOVIR": "TENOFOVIR",
        "EFAVIRENZ": "EFAVIRENZ",
        "NEVIRAPINA": "NEVIRAPINE",
        "LOPINAVIR": "LOPINAVIR",
        "RITONAVIR": "RITONAVIR",
        "ATAZANAVIR": "ATAZANAVIR",
        "DARUNAVIR": "DARUNAVIR",
        "RALTEGRAVIR": "RALTEGRAVIR",
        "DOLUTEGRAVIR": "DOLUTEGRAVIR",
        "SOFOSBUVIR": "SOFOSBUVIR",
        "LEDIPASVIR": "LEDIPASVIR",
        "REMDESIVIR": "REMDESIVIR",

        # 心血管藥物
        "ENALAPRIL": "ENALAPRIL",
        "LISINOPRIL": "LISINOPRIL",
        "CAPTOPRIL": "CAPTOPRIL",
        "RAMIPRIL": "RAMIPRIL",
        "LOSARTANA": "LOSARTAN",
        "LOSARTAN": "LOSARTAN",
        "VALSARTANA": "VALSARTAN",
        "VALSARTAN": "VALSARTAN",
        "TELMISARTANA": "TELMISARTAN",
        "TELMISARTAN": "TELMISARTAN",
        "CANDESARTANA": "CANDESARTAN",
        "CANDESARTAN": "CANDESARTAN",
        "OLMESARTANA": "OLMESARTAN",
        "OLMESARTAN": "OLMESARTAN",
        "AMLODIPINA": "AMLODIPINE",
        "AMLODIPINO": "AMLODIPINE",
        "NIFEDIPINA": "NIFEDIPINE",
        "NIFEDIPINO": "NIFEDIPINE",
        "DILTIAZEM": "DILTIAZEM",
        "VERAPAMIL": "VERAPAMIL",
        "ATENOLOL": "ATENOLOL",
        "METOPROLOL": "METOPROLOL",
        "PROPRANOLOL": "PROPRANOLOL",
        "CARVEDILOL": "CARVEDILOL",
        "BISOPROLOL": "BISOPROLOL",
        "NEBIVOLOL": "NEBIVOLOL",
        "HIDROCLOROTIAZIDA": "HYDROCHLOROTHIAZIDE",
        "INDAPAMIDA": "INDAPAMIDE",
        "CLORTALIDONA": "CHLORTHALIDONE",
        "ESPIRONOLACTONA": "SPIRONOLACTONE",
        "ATORVASTATINA": "ATORVASTATIN",
        "SINVASTATINA": "SIMVASTATIN",
        "ROSUVASTATINA": "ROSUVASTATIN",
        "PRAVASTATINA": "PRAVASTATIN",
        "FLUVASTATINA": "FLUVASTATIN",
        "LOVASTATINA": "LOVASTATIN",
        "EZETIMIBA": "EZETIMIBE",
        "FENOFIBRATO": "FENOFIBRATE",
        "BEZAFIBRATO": "BEZAFIBRATE",
        "GENFIBROZILA": "GEMFIBROZIL",
        "VARFARINA": "WARFARIN",
        "HEPARINA": "HEPARIN",
        "ENOXAPARINA": "ENOXAPARIN",
        "RIVAROXABANA": "RIVAROXABAN",
        "APIXABANA": "APIXABAN",
        "DABIGATRANA": "DABIGATRAN",
        "CLOPIDOGREL": "CLOPIDOGREL",
        "TICAGRELOR": "TICAGRELOR",
        "PRASUGREL": "PRASUGREL",
        "DIGOXINA": "DIGOXIN",
        "AMIODARONA": "AMIODARONE",
        "PROPAFENONA": "PROPAFENONE",
        "SOTALOL": "SOTALOL",
        "NITROGLICERINA": "NITROGLYCERIN",
        "DINITRATO DE ISOSSORBIDA": "ISOSORBIDE DINITRATE",
        "MONONITRATO DE ISOSSORBIDA": "ISOSORBIDE MONONITRATE",

        # 糖尿病藥物
        "METFORMINA": "METFORMIN",
        "GLIBENCLAMIDA": "GLYBURIDE",
        "GLICLAZIDA": "GLICLAZIDE",
        "GLIMEPIRIDA": "GLIMEPIRIDE",
        "GLIPIZIDA": "GLIPIZIDE",
        "PIOGLITAZONA": "PIOGLITAZONE",
        "ROSIGLITAZONA": "ROSIGLITAZONE",
        "SITAGLIPTINA": "SITAGLIPTIN",
        "VILDAGLIPTINA": "VILDAGLIPTIN",
        "SAXAGLIPTINA": "SAXAGLIPTIN",
        "LINAGLIPTINA": "LINAGLIPTIN",
        "EMPAGLIFLOZINA": "EMPAGLIFLOZIN",
        "DAPAGLIFLOZINA": "DAPAGLIFLOZIN",
        "CANAGLIFLOZINA": "CANAGLIFLOZIN",
        "LIRAGLUTIDA": "LIRAGLUTIDE",
        "EXENATIDA": "EXENATIDE",
        "DULAGLUTIDA": "DULAGLUTIDE",
        "SEMAGLUTIDA": "SEMAGLUTIDE",
        "INSULINA": "INSULIN",
        "INSULINA HUMANA": "INSULIN",
        "INSULINA GLARGINA": "INSULIN GLARGINE",
        "INSULINA DETEMIR": "INSULIN DETEMIR",
        "INSULINA DEGLUDECA": "INSULIN DEGLUDEC",
        "INSULINA ASPARTE": "INSULIN ASPART",
        "INSULINA LISPRO": "INSULIN LISPRO",
        "INSULINA GLULISINA": "INSULIN GLULISINE",
        "ACARBOSE": "ACARBOSE",

        # 神經/精神藥物
        "SERTRALINA": "SERTRALINE",
        "FLUOXETINA": "FLUOXETINE",
        "PAROXETINA": "PAROXETINE",
        "ESCITALOPRAM": "ESCITALOPRAM",
        "CITALOPRAM": "CITALOPRAM",
        "VENLAFAXINA": "VENLAFAXINE",
        "DESVENLAFAXINA": "DESVENLAFAXINE",
        "DULOXETINA": "DULOXETINE",
        "BUPROPIONA": "BUPROPION",
        "MIRTAZAPINA": "MIRTAZAPINE",
        "TRAZODONA": "TRAZODONE",
        "AMITRIPTILINA": "AMITRIPTYLINE",
        "NORTRIPTILINA": "NORTRIPTYLINE",
        "IMIPRAMINA": "IMIPRAMINE",
        "CLOMIPRAMINA": "CLOMIPRAMINE",
        "RISPERIDONA": "RISPERIDONE",
        "OLANZAPINA": "OLANZAPINE",
        "QUETIAPINA": "QUETIAPINE",
        "ARIPIPRAZOL": "ARIPIPRAZOLE",
        "HALOPERIDOL": "HALOPERIDOL",
        "CLORPROMAZINA": "CHLORPROMAZINE",
        "LEVOMEPROMAZINA": "LEVOMEPROMAZINE",
        "CLOZAPINA": "CLOZAPINE",
        "ZIPRASIDONA": "ZIPRASIDONE",
        "PALIPERIDONA": "PALIPERIDONE",
        "LÍTIO": "LITHIUM",
        "CARBONATO DE LITIO": "LITHIUM CARBONATE",
        "VALPROATO": "VALPROIC ACID",
        "ÁCIDO VALPRÓICO": "VALPROIC ACID",
        "ÁCIDO VALPROICO": "VALPROIC ACID",
        "CARBAMAZEPINA": "CARBAMAZEPINE",
        "OXCARBAZEPINA": "OXCARBAZEPINE",
        "FENITOÍNA": "PHENYTOIN",
        "FENITOINA": "PHENYTOIN",
        "FENOBARBITAL": "PHENOBARBITAL",
        "LAMOTRIGINA": "LAMOTRIGINE",
        "LEVETIRACETAM": "LEVETIRACETAM",
        "TOPIRAMATO": "TOPIRAMATE",
        "GABAPENTINA": "GABAPENTIN",
        "PREGABALINA": "PREGABALIN",
        "DIAZEPAM": "DIAZEPAM",
        "CLONAZEPAM": "CLONAZEPAM",
        "ALPRAZOLAM": "ALPRAZOLAM",
        "LORAZEPAM": "LORAZEPAM",
        "BROMAZEPAM": "BROMAZEPAM",
        "MIDAZOLAM": "MIDAZOLAM",
        "ZOLPIDEM": "ZOLPIDEM",
        "DONEPEZILA": "DONEPEZIL",
        "RIVASTIGMINA": "RIVASTIGMINE",
        "GALANTAMINA": "GALANTAMINE",
        "MEMANTINA": "MEMANTINE",
        "LEVODOPA": "LEVODOPA",
        "CARBIDOPA": "CARBIDOPA",
        "PRAMIPEXOL": "PRAMIPEXOLE",
        "ROPINIROL": "ROPINIROLE",
        "SELEGILINA": "SELEGILINE",
        "RASAGILINA": "RASAGILINE",
        "ENTACAPONA": "ENTACAPONE",
        "AMANTADINA": "AMANTADINE",

        # 鎮痛藥/消炎藥
        "TRAMADOL": "TRAMADOL",
        "CODEINA": "CODEINE",
        "CODEÍNA": "CODEINE",
        "MORFINA": "MORPHINE",
        "OXICODONA": "OXYCODONE",
        "HIDROCODONA": "HYDROCODONE",
        "FENTANILA": "FENTANYL",
        "FENTANIL": "FENTANYL",
        "METADONA": "METHADONE",
        "BUPRENORFINA": "BUPRENORPHINE",
        "IBUPROFENO": "IBUPROFEN",
        "NAPROXENO": "NAPROXEN",
        "CETOPROFENO": "KETOPROFEN",
        "DICLOFENACO": "DICLOFENAC",
        "PIROXICAM": "PIROXICAM",
        "MELOXICAM": "MELOXICAM",
        "TENOXICAM": "TENOXICAM",
        "NIMESULIDA": "NIMESULIDE",
        "CELECOXIBE": "CELECOXIB",
        "ETORICOXIBE": "ETORICOXIB",
        "INDOMETACINA": "INDOMETHACIN",
        "ACECLOFENACO": "ACECLOFENAC",
        "SULINDACO": "SULINDAC",
        "ETODOLACO": "ETODOLAC",

        # 類固醇
        "PREDNISONA": "PREDNISONE",
        "PREDNISOLONA": "PREDNISOLONE",
        "DEXAMETASONA": "DEXAMETHASONE",
        "BETAMETASONA": "BETAMETHASONE",
        "HIDROCORTISONA": "HYDROCORTISONE",
        "METILPREDNISOLONA": "METHYLPREDNISOLONE",
        "TRIANCINOLONA": "TRIAMCINOLONE",
        "BUDESONIDA": "BUDESONIDE",
        "FLUTICASONA": "FLUTICASONE",
        "BECLOMETASONA": "BECLOMETHASONE",
        "MOMETASONA": "MOMETASONE",
        "CLOBETASOL": "CLOBETASOL",

        # 生物製劑
        "ADALIMUMABE": "ADALIMUMAB",
        "ETANERCEPTE": "ETANERCEPT",
        "INFLIXIMABE": "INFLIXIMAB",
        "GOLIMUMABE": "GOLIMUMAB",
        "CERTOLIZUMABE": "CERTOLIZUMAB",
        "TOCILIZUMABE": "TOCILIZUMAB",
        "RITUXIMABE": "RITUXIMAB",
        "TRASTUZUMABE": "TRASTUZUMAB",
        "BEVACIZUMABE": "BEVACIZUMAB",
        "CETUXIMABE": "CETUXIMAB",
        "PEMBROLIZUMABE": "PEMBROLIZUMAB",
        "NIVOLUMABE": "NIVOLUMAB",
        "ATEZOLIZUMABE": "ATEZOLIZUMAB",
        "DURVALUMABE": "DURVALUMAB",
        "IPILIMUMABE": "IPILIMUMAB",
        "SECUQUINUMABE": "SECUKINUMAB",
        "USTEQUINUMABE": "USTEKINUMAB",
        "ABATACEPTE": "ABATACEPT",
        "NATALIZUMABE": "NATALIZUMAB",
        "VEDOLIZUMABE": "VEDOLIZUMAB",
        "OMALIZUMABE": "OMALIZUMAB",
        "DENOSUMABE": "DENOSUMAB",
        "RANIBIZUMABE": "RANIBIZUMAB",
        "AFLIBERCEPTE": "AFLIBERCEPT",
        "ECULIZUMABE": "ECULIZUMAB",
        "ALEMTUZUMABE": "ALEMTUZUMAB",
        "BASILIXIMABE": "BASILIXIMAB",
        "BELIMUMABE": "BELIMUMAB",
        "BRENTUXIMABE": "BRENTUXIMAB",
        "DARATUMUMABE": "DARATUMUMAB",
        "EMICIZUMABE": "EMICIZUMAB",
        "GUSELCUMABE": "GUSELKUMAB",
        "IXEQUIZUMABE": "IXEKIZUMAB",
        "OBINUTUZUMABE": "OBINUTUZUMAB",
        "OFATUMUMABE": "OFATUMUMAB",
        "PALIVIZUMABE": "PALIVIZUMAB",
        "PANITUMUMABE": "PANITUMUMAB",
        "PERTUZUMABE": "PERTUZUMAB",
        "RAMUCIRUMABE": "RAMUCIRUMAB",
        "RISANQUIZUMABE": "RISANKIZUMAB",
        "SARILUMABE": "SARILUMAB",
        "TILDAQUIZUMABE": "TILDRAKIZUMAB",

        # 抗腫瘤藥物
        "METOTREXATO": "METHOTREXATE",
        "METOTREXATE": "METHOTREXATE",
        "CICLOFOSFAMIDA": "CYCLOPHOSPHAMIDE",
        "IFOSFAMIDA": "IFOSFAMIDE",
        "CISPLATINA": "CISPLATIN",
        "CARBOPLATINA": "CARBOPLATIN",
        "OXALIPLATINA": "OXALIPLATIN",
        "DOXORRUBICINA": "DOXORUBICIN",
        "EPIRRUBICINA": "EPIRUBICIN",
        "DAUNORRUBICINA": "DAUNORUBICIN",
        "MITOXANTRONA": "MITOXANTRONE",
        "VINCRISTINA": "VINCRISTINE",
        "VIMBLASTINA": "VINBLASTINE",
        "VINORELBINA": "VINORELBINE",
        "DOCETAXEL": "DOCETAXEL",
        "PACLITAXEL": "PACLITAXEL",
        "ETOPOSÍDEO": "ETOPOSIDE",
        "ETOPOSIDEO": "ETOPOSIDE",
        "IRINOTECANO": "IRINOTECAN",
        "TOPOTECANO": "TOPOTECAN",
        "GENCITABINA": "GEMCITABINE",
        "CAPECITABINA": "CAPECITABINE",
        "FLUORURACILA": "FLUOROURACIL",
        "5-FLUORURACILA": "FLUOROURACIL",
        "CITARABINA": "CYTARABINE",
        "MERCAPTOPURINA": "MERCAPTOPURINE",
        "AZATIOPRINA": "AZATHIOPRINE",
        "TIOGUANINA": "THIOGUANINE",
        "HIDROXIUREIA": "HYDROXYUREA",
        "BORTEZOMIBE": "BORTEZOMIB",
        "CARFILZOMIBE": "CARFILZOMIB",
        "LENALIDOMIDA": "LENALIDOMIDE",
        "POMALIDOMIDA": "POMALIDOMIDE",
        "TALIDOMIDA": "THALIDOMIDE",
        "IMATINIBE": "IMATINIB",
        "DASATINIBE": "DASATINIB",
        "NILOTINIBE": "NILOTINIB",
        "BOSUTINIBE": "BOSUTINIB",
        "PONATINIBE": "PONATINIB",
        "SORAFENIBE": "SORAFENIB",
        "SUNITINIBE": "SUNITINIB",
        "PAZOPANIBE": "PAZOPANIB",
        "AXITINIBE": "AXITINIB",
        "CABOZANTINIBE": "CABOZANTINIB",
        "REGORAFENIBE": "REGORAFENIB",
        "ERLOTINIBE": "ERLOTINIB",
        "GEFITINIBE": "GEFITINIB",
        "AFATINIBE": "AFATINIB",
        "OSIMERTINIBE": "OSIMERTINIB",
        "LAPATINIBE": "LAPATINIB",
        "CRIZOTINIBE": "CRIZOTINIB",
        "ALECTINIBE": "ALECTINIB",
        "CERITINIBE": "CERITINIB",
        "BRIGATINIBE": "BRIGATINIB",
        "VEMURAFENIBE": "VEMURAFENIB",
        "DABRAFENIBE": "DABRAFENIB",
        "TRAMETINIBE": "TRAMETINIB",
        "COBIMETINIBE": "COBIMETINIB",
        "ENCORAFENIBE": "ENCORAFENIB",
        "BINIMETINIBE": "BINIMETINIB",
        "PALBOCICLIBE": "PALBOCICLIB",
        "RIBOCICLIBE": "RIBOCICLIB",
        "ABEMACICLIBE": "ABEMACICLIB",
        "EVEROLIMO": "EVEROLIMUS",
        "TENSIROLIMO": "TEMSIROLIMUS",
        "IDELALISIBE": "IDELALISIB",
        "IBRUTINIBE": "IBRUTINIB",
        "ACALABRUTINIBE": "ACALABRUTINIB",
        "VENETOCLAX": "VENETOCLAX",
        "RUXOLITINIBE": "RUXOLITINIB",
        "FEDRATINIBE": "FEDRATINIB",
        "OLAPARIBE": "OLAPARIB",
        "NIRAPARIBE": "NIRAPARIB",
        "RUCAPARIBE": "RUCAPARIB",
        "TALAZOPARIBE": "TALAZOPARIB",
        "ENZALUTAMIDA": "ENZALUTAMIDE",
        "ABIRATERONA": "ABIRATERONE",
        "APALUTAMIDA": "APALUTAMIDE",
        "DAROLUTAMIDA": "DAROLUTAMIDE",
        "TAMOXIFENO": "TAMOXIFEN",
        "LETROZOL": "LETROZOLE",
        "ANASTROZOL": "ANASTROZOLE",
        "EXEMESTANO": "EXEMESTANE",
        "FULVESTRANTO": "FULVESTRANT",
        "BICALUTAMIDA": "BICALUTAMIDE",
        "FLUTAMIDA": "FLUTAMIDE",
        "LEUPRORRELINA": "LEUPROLIDE",
        "GOSSERELINA": "GOSERELIN",
        "TRIPTORELINA": "TRIPTORELIN",
        "DEGARELIX": "DEGARELIX",

        # 免疫抑制劑
        "CICLOSPORINA": "CYCLOSPORINE",
        "TACROLIMO": "TACROLIMUS",
        "TACROLIMUS": "TACROLIMUS",
        "SIROLIMO": "SIROLIMUS",
        "SIROLIMUS": "SIROLIMUS",
        "MICOFENOLATO": "MYCOPHENOLIC ACID",
        "MICOFENOLATO DE MOFETILA": "MYCOPHENOLATE MOFETIL",
        "MICOFENOLATO DE SÓDIO": "MYCOPHENOLIC ACID",

        # 呼吸道藥物
        "SALBUTAMOL": "ALBUTEROL",
        "ALBUTEROL": "ALBUTEROL",
        "FENOTEROL": "FENOTEROL",
        "TERBUTALINA": "TERBUTALINE",
        "SALMETEROL": "SALMETEROL",
        "FORMOTEROL": "FORMOTEROL",
        "INDACATEROL": "INDACATEROL",
        "OLODATEROL": "OLODATEROL",
        "VILANTEROL": "VILANTEROL",
        "IPRATRÓPIO": "IPRATROPIUM",
        "IPATROPIO": "IPRATROPIUM",
        "BROMETO DE IPRATRÓPIO": "IPRATROPIUM",
        "TIOTRÓPIO": "TIOTROPIUM",
        "GLICOPIRRÔNIO": "GLYCOPYRRONIUM",
        "UMECLIDÍNIO": "UMECLIDINIUM",
        "ACLIDÍNIO": "ACLIDINIUM",
        "MONTELUCASTE": "MONTELUKAST",
        "ZAFIRLUCASTE": "ZAFIRLUKAST",
        "TEOFILINA": "THEOPHYLLINE",
        "AMINOFILINA": "AMINOPHYLLINE",
        "ACETILCISTEÍNA": "ACETYLCYSTEINE",
        "ACETILCISTEINA": "ACETYLCYSTEINE",
        "CARBOCISTEÍNA": "CARBOCISTEINE",
        "AMBROXOL": "AMBROXOL",
        "BROMEXINA": "BROMHEXINE",
        "DEXTROMETORFANO": "DEXTROMETHORPHAN",

        # 消化道藥物
        "METOCLOPRAMIDA": "METOCLOPRAMIDE",
        "DOMPERIDONA": "DOMPERIDONE",
        "ONDANSETRONA": "ONDANSETRON",
        "GRANISETRONA": "GRANISETRON",
        "TROPISETRONA": "TROPISETRON",
        "LOPERAMIDA": "LOPERAMIDE",
        "SIMETICONA": "SIMETHICONE",
        "DIMETICONA": "DIMETHICONE",
        "LACTULOSE": "LACTULOSE",
        "POLIETILENOGLICOL": "POLYETHYLENE GLYCOL",
        "MACROGOL": "MACROGOL",
        "SULFASSALAZINA": "SULFASALAZINE",
        "MESALAZINA": "MESALAMINE",
        "MESALAMINA": "MESALAMINE",
        "OLSALAZINA": "OLSALAZINE",
        "BALSALAZIDA": "BALSALAZIDE",
        "SUCRALFATO": "SUCRALFATE",
        "BISMUTO": "BISMUTH",
        "SUBSALICILATO DE BISMUTO": "BISMUTH SUBSALICYLATE",
        "ESCOPOLAMINA": "SCOPOLAMINE",
        "BUTILESCOPOLAMINA": "SCOPOLAMINE BUTYLBROMIDE",
        "HIOSCINA": "SCOPOLAMINE",
        "ATROPINA": "ATROPINE",
        "DICICLOMINA": "DICYCLOMINE",
        "DICICLOVERINA": "DICYCLOMINE",
        "MEBEVERINA": "MEBEVERINE",
        "TRIMEBUTINA": "TRIMEBUTINE",
        "PINAVÉRIO": "PINAVERIUM",
        "OTILÔNIO": "OTILONIUM",
        "ÁCIDO URSODESOXICÓLICO": "URSODEOXYCHOLIC ACID",
        "URSODIOL": "URSODEOXYCHOLIC ACID",

        # 抗組胺藥/過敏藥
        "DIFENIDRAMINA": "DIPHENHYDRAMINE",
        "CLORFENIRAMINA": "CHLORPHENIRAMINE",
        "DEXCLORFENIRAMINA": "DEXCHLORPHENIRAMINE",
        "PROMETAZINA": "PROMETHAZINE",
        "HIDROXIZINA": "HYDROXYZINE",
        "CETIRIZINA": "CETIRIZINE",
        "LEVOCETIRIZINA": "LEVOCETIRIZINE",
        "LORATADINA": "LORATADINE",
        "DESLORATADINA": "DESLORATADINE",
        "FEXOFENADINA": "FEXOFENADINE",
        "BILASTINA": "BILASTINE",
        "RUPATADINA": "RUPATADINE",
        "EBASTINA": "EBASTINE",
        "AZELASTINA": "AZELASTINE",
        "OLOPATADINA": "OLOPATADINE",
        "CROMOGLICATO": "CROMOLYN",
        "CROMOGLICATO DE SÓDIO": "CROMOLYN SODIUM",
        "CETOTIFENO": "KETOTIFEN",

        # 泌尿藥物
        "TANSULOSINA": "TAMSULOSIN",
        "ALFUZOSINA": "ALFUZOSIN",
        "DOXAZOSINA": "DOXAZOSIN",
        "SILODOSINA": "SILODOSIN",
        "FINASTERIDA": "FINASTERIDE",
        "DUTASTERIDA": "DUTASTERIDE",
        "TOLTERODINA": "TOLTERODINE",
        "OXIBUTININA": "OXYBUTYNIN",
        "SOLIFENACINA": "SOLIFENACIN",
        "DARIFENACINA": "DARIFENACIN",
        "FESOTERODINA": "FESOTERODINE",
        "MIRABEGRONA": "MIRABEGRON",
        "SILDENAFILA": "SILDENAFIL",
        "TADALAFILA": "TADALAFIL",
        "VARDENAFILA": "VARDENAFIL",
        "AVANAFILA": "AVANAFIL",

        # 骨質疏鬆藥物
        "ALENDRONATO": "ALENDRONATE",
        "RISEDRONATO": "RISEDRONATE",
        "IBANDRONATO": "IBANDRONATE",
        "ZOLEDRONATO": "ZOLEDRONIC ACID",
        "ÁCIDO ZOLEDRÔNICO": "ZOLEDRONIC ACID",
        "PAMIDRONATO": "PAMIDRONATE",
        "RALOXIFENO": "RALOXIFENE",
        "BAZEDOXIFENO": "BAZEDOXIFENE",
        "TERIPARATIDA": "TERIPARATIDE",
        "ROMOSOZUMABE": "ROMOSOZUMAB",
        "CALCITONINA": "CALCITONIN",

        # 眼科藥物
        "LATANOPROSTA": "LATANOPROST",
        "BIMATOPROSTA": "BIMATOPROST",
        "TRAVOPROSTA": "TRAVOPROST",
        "TAFLUPROST": "TAFLUPROST",
        "TIMOLOL": "TIMOLOL",
        "BETAXOLOL": "BETAXOLOL",
        "DORZOLAMIDA": "DORZOLAMIDE",
        "BRINZOLAMIDA": "BRINZOLAMIDE",
        "PILOCARPINA": "PILOCARPINE",
        "BRIMONIDINA": "BRIMONIDINE",
        "APRACLONIDINA": "APRACLONIDINE",
        "CICLOPENTOLATO": "CYCLOPENTOLATE",
        "TROPICAMIDA": "TROPICAMIDE",
        "FENILEFRINA": "PHENYLEPHRINE",
        "NEPAFENACO": "NEPAFENAC",
        "CETOROLACO": "KETOROLAC",
        "DICLOFENACO OFTÁLMICO": "DICLOFENAC",

        # 皮膚科藥物
        "ISOTRETINOÍNA": "ISOTRETINOIN",
        "ISOTRETINOINA": "ISOTRETINOIN",
        "TRETINOÍNA": "TRETINOIN",
        "TRETINOINA": "TRETINOIN",
        "ADAPALENO": "ADAPALENE",
        "TAZAROTENO": "TAZAROTENE",
        "PERÓXIDO DE BENZOÍLA": "BENZOYL PEROXIDE",
        "ÁCIDO AZELAICO": "AZELAIC ACID",
        "ERITROMICINA TÓPICA": "ERYTHROMYCIN",
        "CLINDAMICINA TÓPICA": "CLINDAMYCIN",
        "METRONIDAZOL TÓPICO": "METRONIDAZOLE",
        "IVERMECTINA TÓPICA": "IVERMECTIN",
        "MINOXIDIL": "MINOXIDIL",
        "FINASTERIDA": "FINASTERIDE",
        "CALCIPOTRIOL": "CALCIPOTRIOL",
        "CALCITRIOL": "CALCITRIOL",
        "TACALCITOL": "TACALCITOL",
        "PIMECROLIMO": "PIMECROLIMUS",
        "TACROLIMO TÓPICO": "TACROLIMUS",
        "IMIQUIMODE": "IMIQUIMOD",
        "PODOFILOTOXINA": "PODOPHYLLOTOXIN",
        "CROTAMITONA": "CROTAMITON",
        "BENZOATO DE BENZILA": "BENZYL BENZOATE",
        "PERMETRINA": "PERMETHRIN",
        "LINDANO": "LINDANE",
        "MALATIONA": "MALATHION",

        # 荷爾蒙藥物
        "ESTRADIOL": "ESTRADIOL",
        "ETINILESTRADIOL": "ETHINYLESTRADIOL",
        "ESTRIOL": "ESTRIOL",
        "ESTROGÊNIOS CONJUGADOS": "CONJUGATED ESTROGENS",
        "PROGESTERONA": "PROGESTERONE",
        "MEDROXIPROGESTERONA": "MEDROXYPROGESTERONE",
        "NORETISTERONA": "NORETHISTERONE",
        "LEVONORGESTREL": "LEVONORGESTREL",
        "DESOGESTREL": "DESOGESTREL",
        "GESTODENO": "GESTODENE",
        "NORGESTIMATO": "NORGESTIMATE",
        "DROSPIRENONA": "DROSPIRENONE",
        "DIENOGESTE": "DIENOGEST",
        "NOMEGESTROL": "NOMEGESTROL",
        "ETONOGESTREL": "ETONOGESTREL",
        "TESTOSTERONA": "TESTOSTERONE",
        "UNDECANOATO DE TESTOSTERONA": "TESTOSTERONE UNDECANOATE",
        "LEVOTIROXINA": "LEVOTHYROXINE",
        "LIOTIRONINA": "LIOTHYRONINE",
        "PROPILTIOURACILA": "PROPYLTHIOURACIL",
        "METIMAZOL": "METHIMAZOLE",
        "CARBIMAZOL": "CARBIMAZOLE",

        # 其他常見藥物
        "COLCHICINA": "COLCHICINE",
        "ALOPURINOL": "ALLOPURINOL",
        "FEBUXOSTAT": "FEBUXOSTAT",
        "LEFLUNOMIDA": "LEFLUNOMIDE",
        "SULFASSALAZINA": "SULFASALAZINE",
        "HIDROXICLOROQUINA": "HYDROXYCHLOROQUINE",
        "CLOROQUINA": "CHLOROQUINE",
        "PENICILAMINA": "PENICILLAMINE",
        "AURANOFINA": "AURANOFIN",
        "DEFEROXAMINA": "DEFEROXAMINE",
        "DEFERIPRONA": "DEFERIPRONE",
        "DEFERASIROX": "DEFERASIROX",
        "FILGRASTIM": "FILGRASTIM",
        "PEGFILGRASTIM": "PEGFILGRASTIM",
        "ERITROPOETINA": "ERYTHROPOIETIN",
        "DARBEPOETINA": "DARBEPOETIN ALFA",
        "OPRELVEKIN": "OPRELVEKIN",
        "ROMIPLOSTIM": "ROMIPLOSTIM",
        "ELTROMBOPAG": "ELTROMBOPAG",
        "FATOR VIII": "FACTOR VIII",
        "FATOR IX": "FACTOR IX",

        # 電解質/礦物質葡萄牙文
        "CLORETO DE SÓDIO": "SODIUM CHLORIDE",
        "CLORETO DE POTÁSSIO": "POTASSIUM CHLORIDE",
        "CLORETO DE CÁLCIO": "CALCIUM CHLORIDE",
        "CLORETO DE MAGNÉSIO": "MAGNESIUM CHLORIDE",
        "GLUCONATO DE CÁLCIO": "CALCIUM GLUCONATE",
        "SULFATO DE MAGNÉSIO": "MAGNESIUM SULFATE",
        "BICARBONATO DE SÓDIO": "SODIUM BICARBONATE",
        "CARBONATO DE CÁLCIO": "CALCIUM CARBONATE",
        "FOSFATO DE SÓDIO": "SODIUM PHOSPHATE",
        "SULFATO FERROSO": "FERROUS SULFATE",
        "SULFATO DE ZINCO": "ZINC SULFATE",
        "ÓXIDO DE ZINCO": "ZINC OXIDE",

        # 抗寄生蟲藥
        "ALBENDAZOL": "ALBENDAZOLE",
        "MEBENDAZOL": "MEBENDAZOLE",
        "TIABENDAZOL": "THIABENDAZOLE",
        "IVERMECTINA": "IVERMECTIN",
        "PRAZIQUANTEL": "PRAZIQUANTEL",
        "NICLOSAMIDA": "NICLOSAMIDE",
        "NITAZOXANIDA": "NITAZOXANIDE",
        "LEVAMISOL": "LEVAMISOLE",
        "PIRANTEL": "PYRANTEL",
        "PAMOATO DE PIRANTEL": "PYRANTEL",
        "SECNIDAZOL": "SECNIDAZOLE",
        "TINIDAZOL": "TINIDAZOLE",
        "BENZNIDAZOL": "BENZNIDAZOLE",
        "NIFURTIMOX": "NIFURTIMOX",
        "MEFLOQUINA": "MEFLOQUINE",
        "PRIMAQUINA": "PRIMAQUINE",
        "QUININA": "QUININE",
        "ARTEMETER": "ARTEMETHER",
        "ARTESUNATO": "ARTESUNATE",
        "LUMEFANTRINA": "LUMEFANTRINE",
        "ATOVAQUONA": "ATOVAQUONE",
        "PROGUANIL": "PROGUANIL",
        "PIRIMETAMINA": "PYRIMETHAMINE",
        "SULFADOXINA": "SULFADOXINE",
        "DAPSONA": "DAPSONE",
        "ANFOTERICINA B LIPOSSOMAL": "AMPHOTERICIN B",
        "PENTAMIDINA": "PENTAMIDINE",
        "MILTEFOSINA": "MILTEFOSINE",
        "ESTIBOGLUCONATO DE SÓDIO": "SODIUM STIBOGLUCONATE",
        "GLUCANTIME": "MEGLUMINE ANTIMONIATE",
        "ANTIMONIATO DE MEGLUMINA": "MEGLUMINE ANTIMONIATE",

        # 疫苗相關
        "TOXÓIDE TETÂNICO": "TETANUS TOXOID",
        "TOXÓIDE DIFTÉRICO": "DIPHTHERIA TOXOID",
        "VACINA BCG": "BCG VACCINE",
        "HEPATITE B RECOMBINANTE": "HEPATITIS B VACCINE",
        "VACINA PNEUMOCÓCICA": "PNEUMOCOCCAL VACCINE",
        "VACINA MENINGOCÓCICA": "MENINGOCOCCAL VACCINE",
        "VACINA CONTRA INFLUENZA": "INFLUENZA VACCINE",
        "VACINA HPV": "HPV VACCINE",

        # 造影劑
        "IOHEXOL": "IOHEXOL",
        "IOPAMIDOL": "IOPAMIDOL",
        "IOVERSOL": "IOVERSOL",
        "IOMEPROL": "IOMEPROL",
        "IOPROMIDA": "IOPROMIDE",
        "IOBITRIDOL": "IOBITRIDOL",
        "GADOLÍNIO": "GADOLINIUM",
        "GADOPENTETATO": "GADOPENTETIC ACID",
        "GADOBUTROL": "GADOBUTROL",
        "GADOTERIDOL": "GADOTERIDOL",
        "GADODIAMIDA": "GADODIAMIDE",
        "SULFATO DE BÁRIO": "BARIUM SULFATE",

        # 麻醉藥
        "PROPOFOL": "PROPOFOL",
        "ETOMIDATO": "ETOMIDATE",
        "CETAMINA": "KETAMINE",
        "TIOPENTAL": "THIOPENTAL",
        "SEVOFLURANO": "SEVOFLURANE",
        "DESFLURANO": "DESFLURANE",
        "ISOFLURANO": "ISOFLURANE",
        "ÓXIDO NITROSO": "NITROUS OXIDE",
        "LIDOCAÍNA": "LIDOCAINE",
        "BUPIVACAÍNA": "BUPIVACAINE",
        "ROPIVACAÍNA": "ROPIVACAINE",
        "LEVOBUPIVACAÍNA": "LEVOBUPIVACAINE",
        "PRILOCAÍNA": "PRILOCAINE",
        "MEPIVACAÍNA": "MEPIVACAINE",
        "ARTICAÍNA": "ARTICAINE",
        "TETRACAÍNA": "TETRACAINE",
        "BENZOCAÍNA": "BENZOCAINE",
        "SUCCINILCOLINA": "SUCCINYLCHOLINE",
        "ROCURÔNIO": "ROCURONIUM",
        "VECURÔNIO": "VECURONIUM",
        "ATRACÚRIO": "ATRACURIUM",
        "CISATRACÚRIO": "CISATRACURIUM",
        "PANCURÔNIO": "PANCURONIUM",
        "NEOSTIGMINA": "NEOSTIGMINE",
        "PIRIDOSTIGMINA": "PYRIDOSTIGMINE",
        "SUGAMMADEX": "SUGAMMADEX",
        "NALOXONA": "NALOXONE",
        "FLUMAZENIL": "FLUMAZENIL",

        # 胺基酸 (葡萄牙文)
        "ALANINA": "ALANINE",
        "ARGININA": "ARGININE",
        "ASPARAGINA": "ASPARAGINE",
        "CISTEINA": "CYSTEINE",
        "CISTEÍNA": "CYSTEINE",
        "GLICINA": "GLYCINE",
        "GLUTAMINA": "GLUTAMINE",
        "HISTIDINA": "HISTIDINE",
        "ISOLEUCINA": "ISOLEUCINE",
        "LEUCINA": "LEUCINE",
        "LISINA": "LYSINE",
        "METIONINA": "METHIONINE",
        "FENILALANINA": "PHENYLALANINE",
        "PROLINA": "PROLINE",
        "SERINA": "SERINE",
        "TREONINA": "THREONINE",
        "TRIPTOFANO": "TRYPTOPHAN",
        "TIROSINA": "TYROSINE",
        "VALINA": "VALINE",
        "TAURINA": "TAURINE",
        "CARNITINA": "CARNITINE",
        "L-CARNITINA": "CARNITINE",
        "ACETIL-L-CARNITINA": "ACETYLCARNITINE",
        "CREATINA": "CREATINE",
        "ORNITINA": "ORNITHINE",
        "CITRULINA": "CITRULLINE",

        # 維生素葡萄牙文
        "VITAMINA A": "VITAMIN A",
        "RETINOL": "VITAMIN A",
        "VITAMINA B1": "THIAMINE",
        "TIAMINA": "THIAMINE",
        "VITAMINA B2": "RIBOFLAVIN",
        "RIBOFLAVINA": "RIBOFLAVIN",
        "VITAMINA B3": "NIACIN",
        "NIACINA": "NIACIN",
        "NICOTINAMIDA": "NICOTINAMIDE",
        "VITAMINA B5": "PANTOTHENIC ACID",
        "ÁCIDO PANTOTÊNICO": "PANTOTHENIC ACID",
        "PANTOTENATO DE CÁLCIO": "CALCIUM PANTOTHENATE",
        "VITAMINA B6": "PYRIDOXINE",
        "PIRIDOXINA": "PYRIDOXINE",
        "VITAMINA B7": "BIOTIN",
        "BIOTINA": "BIOTIN",
        "VITAMINA B9": "FOLIC ACID",
        "ÁCIDO FÓLICO": "FOLIC ACID",
        "FOLATO": "FOLIC ACID",
        "VITAMINA B12": "CYANOCOBALAMIN",
        "CIANOCOBALAMINA": "CYANOCOBALAMIN",
        "HIDROXOCOBALAMINA": "HYDROXOCOBALAMIN",
        "VITAMINA C": "ASCORBIC ACID",
        "ÁCIDO ASCÓRBICO": "ASCORBIC ACID",
        "VITAMINA D": "VITAMIN D",
        "VITAMINA D2": "ERGOCALCIFEROL",
        "ERGOCALCIFEROL": "ERGOCALCIFEROL",
        "VITAMINA D3": "CHOLECALCIFEROL",
        "COLECALCIFEROL": "CHOLECALCIFEROL",
        "VITAMINA E": "VITAMIN E",
        "TOCOFEROL": "VITAMIN E",
        "ALFA-TOCOFEROL": "VITAMIN E",
        "VITAMINA K": "VITAMIN K",
        "VITAMINA K1": "PHYTONADIONE",
        "FITOMENADIONA": "PHYTONADIONE",
        "VITAMINA K2": "MENAQUINONE",
        "MENAQUINONA": "MENAQUINONE",

        # 抗帕金森藥物補充
        "BENSERAZIDA": "BENSERAZIDE",
        "APOMORFINA": "APOMORPHINE",
        "BROMOCRIPTINA": "BROMOCRIPTINE",
        "CABERGOLINA": "CABERGOLINE",
        "PERGOLIDA": "PERGOLIDE",
        "SAFINAMIDA": "SAFINAMIDE",
        "OPICAPONA": "OPICAPONE",
        "TOLCAPONA": "TOLCAPONE",
        "TRIEXIFENIDILA": "TRIHEXYPHENIDYL",
        "BIPERIDENO": "BIPERIDEN",

        # 肌肉鬆弛劑
        "CICLOBENZAPRINA": "CYCLOBENZAPRINE",
        "CARISOPRODOL": "CARISOPRODOL",
        "METOCARBAMOL": "METHOCARBAMOL",
        "ORFENADRINA": "ORPHENADRINE",
        "TIZANIDINA": "TIZANIDINE",
        "BACLOFENO": "BACLOFEN",
        "DANTROLENO": "DANTROLENE",
        "TOXINA BOTULÍNICA": "BOTULINUM TOXIN",
        "TOXINA BOTULINICA": "BOTULINUM TOXIN",
        "TOXINA BOTULÍNICA TIPO A": "BOTULINUM TOXIN TYPE A",

        # 抗凝血酶/血栓藥物
        "ALTEPLASE": "ALTEPLASE",
        "TENECTEPLASE": "TENECTEPLASE",
        "RETEPLASE": "RETEPLASE",
        "ESTREPTOQUINASE": "STREPTOKINASE",
        "UROQUINASE": "UROKINASE",
        "ÁCIDO TRANEXÂMICO": "TRANEXAMIC ACID",
        "ÁCIDO AMINOCAPRÓICO": "AMINOCAPROIC ACID",
        "PROTAMINA": "PROTAMINE",
        "FITOMENADIONA": "PHYTONADIONE",
        "IDARUCIZUMABE": "IDARUCIZUMAB",
        "ANDEXANETE": "ANDEXANET ALFA",
        "FONDAPARINUX": "FONDAPARINUX",
        "DALTEPARINA": "DALTEPARIN",
        "TINZAPARINA": "TINZAPARIN",
        "NADROPARINA": "NADROPARIN",
        "BEMIPARINA": "BEMIPARIN",

        # 鎮靜/安眠藥補充
        "ESZOPICLONA": "ESZOPICLONE",
        "ZOPICLONA": "ZOPICLONE",
        "ZALEPLON": "ZALEPLON",
        "MELATONINA": "MELATONIN",
        "RAMELTEON": "RAMELTEON",
        "SUVOREXANTO": "SUVOREXANT",
        "LEMBOREXANTO": "LEMBOREXANT",
        "DOXILAMINA": "DOXYLAMINE",
        "TIOPENTAL SÓDICO": "THIOPENTAL",
        "PENTOBARBITAL": "PENTOBARBITAL",
        "SECOBARBITAL": "SECOBARBITAL",
        "CLORDIAZEPÓXIDO": "CHLORDIAZEPOXIDE",
        "CLORAZEPATO": "CLORAZEPATE",
        "FLURAZEPAM": "FLURAZEPAM",
        "TRIAZOLAM": "TRIAZOLAM",
        "TEMAZEPAM": "TEMAZEPAM",
        "ESTAZOLAM": "ESTAZOLAM",
        "QUAZEPAM": "QUAZEPAM",

        # 糖尿病藥物補充
        "REPAGLINIDA": "REPAGLINIDE",
        "NATEGLINIDA": "NATEGLINIDE",
        "ALOGLIPTINA": "ALOGLIPTIN",
        "ERTUGLIFLOZINA": "ERTUGLIFLOZIN",
        "BEXAGLIFLOZINA": "BEXAGLIFLOZIN",
        "TIRZEPATIDA": "TIRZEPATIDE",

        # 抗過敏/免疫藥物補充
        "MONTELEUCASTE": "MONTELUKAST",
        "CROMOLINA": "CROMOLYN",
        "NEDOCROMIL": "NEDOCROMIL",
        "EPINASTINA": "EPINASTINE",
        "ALCAFTADINA": "ALCAFTADINE",
        "BEPOTASTINA": "BEPOTASTINE",
    }

    for alias, canonical in synonym_map.items():
        if canonical in index and alias not in index:
            index[alias] = index[canonical]

    return index


def map_ingredient_to_drugbank(
    ingredient: str,
    name_index: Dict[str, str],
) -> Optional[str]:
    """將單一成分映射到 DrugBank ID

    映射策略（優先順序）：
    1. 完全匹配
    2. 移除鹽類後綴後匹配
    3. 使用基本名稱匹配

    Args:
        ingredient: 標準化後的成分名稱
        name_index: 名稱索引

    Returns:
        DrugBank ID，若無法映射則回傳 None
    """
    if not ingredient:
        return None

    ingredient = ingredient.upper().strip()

    # 1. 完全匹配
    if ingredient in name_index:
        return name_index[ingredient]

    # 2. 移除常見鹽類後綴（英文）
    salt_patterns = [
        r"\s+HCL$", r"\s+HYDROCHLORIDE$", r"\s+SODIUM$",
        r"\s+POTASSIUM$", r"\s+SULFATE$", r"\s+MALEATE$",
        r"\s+ACETATE$", r"\s+CITRATE$", r"\s+PHOSPHATE$",
        r"\s+BROMIDE$", r"\s+CHLORIDE$", r"\s+TARTRATE$",
        r"\s+HBR$", r"\s+HYDROBROMIDE$", r"\s+FUMARATE$",
        r"\s+SUCCINATE$", r"\s+MESYLATE$", r"\s+BESYLATE$",
        r"\s+CALCIUM$", r"\s+MAGNESIUM$", r"\s+NITRATE$",
        r"\s+LACTATE$", r"\s+GLUCONATE$", r"\s+DISODIUM$",
        r"\s+ANHYDROUS$", r"\s+MONOHYDRATE$", r"\s+DIHYDRATE$",
        r"\s+TRIHYDRATE$", r"\s+HEXAHYDRATE$",
        r"\s+DIPROPIONATE$", r"\s+PROPIONATE$", r"\s+ACETONIDE$",
        r"\s+VALERATE$", r"\s+BUTYRATE$", r"\s+MONONITRATE$",
    ]

    base_ingredient = ingredient
    for pattern in salt_patterns:
        base_ingredient = re.sub(pattern, "", base_ingredient)

    if base_ingredient != ingredient and base_ingredient in name_index:
        return name_index[base_ingredient]

    # 2b. 移除葡萄牙文鹽類後綴（ANVISA 特有）
    pt_salt_patterns = [
        r"\s+DE SODIUM$", r"\s+DE SÓDIO$", r"\s+SÓDICO$",
        r"\s+DE POTÁSSIO$", r"\s+POTÁSSICO$",
        r"\s+DE CÁLCIO$", r"\s+CÁLCICO$",
        r"\s+DE MAGNÉSIO$",
        r"\s+CLORIDRATO$", r"\s+HIDROCLORETO$",
        r"\s+SULFATO$", r"\s+FOSFATO$", r"\s+ACETATO$",
        r"\s+CITRATO$", r"\s+MALEATO$", r"\s+FUMARATO$",
        r"\s+SUCCINATO$", r"\s+TARTARATO$", r"\s+LACTATO$",
        r"\s+GLUCONATO$", r"\s+NITRATO$", r"\s+BROMETO$",
        r"\s+CLORETO$", r"\s+PROPIONATO$", r"\s+VALERATO$",
        r"\s+BUTIRATO$", r"\s+ACETONIDA$", r"\s+DIPROPIONATO$",
        r"\s+ANIDRO$", r"\s+MONOIDRATO$", r"\s+DIIDRATO$",
        r"\s+TRIIDRATO$", r"\s+HEXAIDRATO$", r"\s+HIDRATADO$",
        r"\s+MICRONIZADO$",
    ]

    base_ingredient = ingredient
    for pattern in pt_salt_patterns:
        base_ingredient = re.sub(pattern, "", base_ingredient)

    if base_ingredient != ingredient and base_ingredient in name_index:
        return name_index[base_ingredient]

    # 2c. 處理 "DE + 藥物" 格式（例：ACETATO DE DEXAMETHASONE → DEXAMETHASONE）
    pt_prefix_patterns = [
        r"^ACETATO DE\s+", r"^FOSFATO DE\s+", r"^SULFATO DE\s+",
        r"^CLORIDRATO DE\s+", r"^CITRATO DE\s+", r"^MALEATO DE\s+",
        r"^SUCCINATO DE\s+", r"^FUMARATO DE\s+", r"^TARTARATO DE\s+",
        r"^NITRATO DE\s+", r"^PROPIONATO DE\s+", r"^VALERATO DE\s+",
        r"^ACETONIDA DE\s+", r"^DIPROPIONATO DE\s+", r"^BUTIRATO DE\s+",
        r"^GLUCONATO DE\s+", r"^LACTATO DE\s+", r"^BROMETO DE\s+",
        r"^CLORETO DE\s+",
        r"^17-BUTIRATO DE\s+", r"^17-VALERATO DE\s+",
        r"^21-ACETATO DE\s+", r"^21-FOSFATO DE\s+",
    ]

    base_ingredient = ingredient
    for pattern in pt_prefix_patterns:
        base_ingredient = re.sub(pattern, "", base_ingredient)

    if base_ingredient != ingredient and base_ingredient in name_index:
        return name_index[base_ingredient]

    # 2d. 移除 L-/D-/DL- 前綴
    prefix_patterns = [r"^L-", r"^D-", r"^DL-", r"^ALFA-", r"^BETA-"]
    base_ingredient = ingredient
    for pattern in prefix_patterns:
        base_ingredient = re.sub(pattern, "", base_ingredient)

    if base_ingredient != ingredient and base_ingredient in name_index:
        return name_index[base_ingredient]

    # 3. 嘗試移除括號內容
    base_ingredient = re.sub(r"\s*\([^)]*\)", "", ingredient).strip()
    if base_ingredient != ingredient and base_ingredient in name_index:
        return name_index[base_ingredient]

    # 4. 嘗試轉換葡萄牙文後綴到英文
    pt_to_en_suffix = [
        (r"INA$", "INE"),      # ASPIRINA → ASPIRIN (但通常是 ASPIRINE)
        (r"OL$", "OL"),        # 保持不變
        (r"IDA$", "IDE"),      # AMOXICILIDA → AMOXICILIDE (不常見)
        (r"ATO$", "ATE"),      # ACETATO → ACETATE
        (r"ICO$", "IC"),       # ASCÓRBICO → ASCORBIC
    ]

    base_ingredient = ingredient
    for pt_suffix, en_suffix in pt_to_en_suffix:
        if re.search(pt_suffix, base_ingredient):
            base_ingredient = re.sub(pt_suffix, en_suffix, base_ingredient)
            if base_ingredient in name_index:
                return name_index[base_ingredient]

    return None


def map_fda_drugs_to_drugbank(
    fda_df: pd.DataFrame,
    drugbank_df: Optional[pd.DataFrame] = None,
    field_mapping: Optional[Dict[str, str]] = None,
) -> pd.DataFrame:
    """將 FDA 藥品映射到 DrugBank

    Args:
        fda_df: FDA 藥品 DataFrame
        drugbank_df: DrugBank 詞彙表（可選）
        field_mapping: 欄位映射（可選），格式如 {"license_id": "NUMERO_REGISTRO_PRODUTO", ...}

    Returns:
        包含映射結果的 DataFrame
    """
    if drugbank_df is None:
        drugbank_df = load_drugbank_vocab()

    # 預設欄位名稱（巴西 ANVISA）
    if field_mapping is None:
        field_mapping = {
            "license_id": "NUMERO_REGISTRO_PRODUTO",
            "brand_name": "NOME_PRODUTO",
            "ingredients": "PRINCIPIO_ATIVO",
        }

    license_col = field_mapping.get("license_id", "NUMERO_REGISTRO_PRODUTO")
    brand_col = field_mapping.get("brand_name", "NOME_PRODUTO")
    ingredient_col = field_mapping.get("ingredients", "PRINCIPIO_ATIVO")

    # 建立索引
    name_index = build_name_index(drugbank_df)

    results = []

    for _, row in fda_df.iterrows():
        ingredient_str = row.get(ingredient_col, "")
        if not ingredient_str or pd.isna(ingredient_str):
            continue

        # 提取所有成分及同義詞
        synonyms_data = get_all_synonyms(str(ingredient_str))

        for main_name, synonyms in synonyms_data:
            drugbank_id = None
            mapping_source = "failed"

            # 先嘗試主名稱
            drugbank_id = map_ingredient_to_drugbank(main_name, name_index)
            if drugbank_id:
                mapping_source = "drugbank"

            # 若失敗，嘗試同義詞
            if drugbank_id is None:
                for syn in synonyms:
                    drugbank_id = map_ingredient_to_drugbank(syn, name_index)
                    if drugbank_id:
                        mapping_source = "drugbank_synonym"
                        break

            results.append({
                "license_id": row.get(license_col, ""),
                "brand_name": row.get(brand_col, ""),
                "original_ingredient": ingredient_str,
                "normalized_ingredient": main_name,
                "synonyms": "; ".join(synonyms) if synonyms else "",
                "drugbank_id": drugbank_id,
                "mapping_success": drugbank_id is not None,
                "mapping_source": mapping_source,
            })

    return pd.DataFrame(results)


def get_mapping_stats(mapping_df: pd.DataFrame) -> dict:
    """計算映射統計

    Args:
        mapping_df: 映射結果 DataFrame

    Returns:
        統計字典
    """
    total = len(mapping_df)
    success = mapping_df["mapping_success"].sum()
    unique_ingredients = mapping_df["normalized_ingredient"].nunique()
    unique_drugbank = mapping_df[mapping_df["mapping_success"]]["drugbank_id"].nunique()

    return {
        "total_ingredients": total,
        "mapped_ingredients": int(success),
        "mapping_rate": success / total if total > 0 else 0,
        "unique_ingredients": unique_ingredients,
        "unique_drugbank_ids": unique_drugbank,
    }
